name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Build
        run: make build
      - name: Commit and tag
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: "bin/cli"
          author_name: Commit Bot
          author_email: contact@usecloudstate.io
          message: "Release v${{ github.run_number }}"
          push: true
          tag: "v${{ github.run_number }}"
      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ github.run_number }}"
          files: |
            bin/cli
      - name: Publish to homebrew tap
        uses: izumin5210/action-homebrew-tap@latest
        with:
          tap: usecloudstate/homebrew-cli
          token: ${{ secrets.GITHUB_TOKEN }}
